name: "✨ Add a new design"
description: "RIDP staff: Add a youth design to the Third Spaces Gallery"
title: "[Design] "
labels: ["new-submission", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🎨 Add a youth design to the gallery

        **For RIDP staff only.** Fill out the details below to add a youth design submission. After submitting, upload screenshots as a comment. Then add the `approved` label to auto-generate the submission PR.

        ---

  - type: input
    id: title
    attributes:
      label: "Design Title"
      description: "Name of the youth's design"
      placeholder: "Third Spaces Explorer"
    validations:
      required: true

  - type: input
    id: designer
    attributes:
      label: "Designer Name(s)"
      description: "Youth designer(s) — first name + last initial"
      placeholder: "Emma G. & Emilia B."
    validations:
      required: true

  - type: input
    id: school
    attributes:
      label: "School"
      description: "Designer's school"
      placeholder: "Rawson Saunders School"
    validations:
      required: true

  - type: dropdown
    id: grade
    attributes:
      label: "Grade Level"
      description: "Designer's grade level"
      options:
        - "Elementary (K-5)"
        - "Middle School (6-8)"
        - "High School (9-12)"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Quick Summary"
      description: "1-2 sentence description of what the design does"
      placeholder: "An app that helps kids find fun places near them based on their interests."
    validations:
      required: true

  - type: checkboxes
    id: features
    attributes:
      label: "What features does this design focus on?"
      description: "Check all that apply"
      options:
        - label: "🔍 Discovery & Search (finding places)"
        - label: "🗺️ Maps & Navigation (getting there)"
        - label: "⭐ Ratings & Feedback (sharing experiences)"
        - label: "🤖 AI Assistant (smart help)"
        - label: "♿ Accessibility (works for everyone)"
        - label: "💬 Communication (messaging, sharing)"

  - type: textarea
    id: description
    attributes:
      label: "Full Description"
      description: "Detailed description of the design — what inspired it, what problem it solves, how it works"
      placeholder: |
        This design addresses the problem of kids not knowing about cool places in their neighborhood.

        Key features:
        - Pick your interests (gaming, sports, art, etc.)
        - See places nearby on a map
        - Get directions by walking, bus, or car
        - Rate places and see what other kids think
    validations:
      required: false

  - type: textarea
    id: creator_note
    attributes:
      label: "Designer's Note (optional)"
      description: "A personal note from the designer about their inspiration (ask or paraphrase)"
      placeholder: "I built this because I noticed kids in my neighborhood don't know about all the cool places nearby..."
    validations:
      required: false

  - type: input
    id: demo_url
    attributes:
      label: "Demo Link (optional)"
      description: "Link to Figma, Canva, or other interactive prototype"
      placeholder: "https://figma.com/..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        ## 📸 Screenshots

        After submitting this form, **upload the design screenshots** by dragging them into a comment below.

        Tips:
        - Include 2-5 screenshots showing different screens
        - The first image becomes the thumbnail
        - The workflow will attempt to auto-download images from comments

  - type: checkboxes
    id: consent
    attributes:
      label: "Staff Confirmation"
      description: "Confirm before submitting"
      options:
        - label: "I have obtained permission to share this design publicly"
          required: true
        - label: "The designer's name and school will be displayed on the gallery"
          required: true
